### ISSUE TITLE
zsh compatibility

### ISSUE THREAD

**Issue by siddharthist** [dylanaraps/wal#5]
The README states that `bash` is a dependency. Does this script work with ZSH? Is there anything in particular that prevents cross-compatibility?

**Comment by dylanaraps** [comment]
`wal` only requires `bash` to be executed, your current shell doesn't matter.

If you're talking about modifying the shebang at the top of the script to be `#!/usr/bin/zsh` then no, this will not work. `wal` was written using various `bash` only features which is why `bash` is a required dependency.

**Comment by siddharthist** [comment]
okay, thanks for the clarification!
